title: OpenSfera
email:
description: >- # this means to ignore newlines until "baseurl:"
  growbox on your screen
baseurl: "/blog"
url: "https://opensfera.github.io"
twitter_username:
github_username:

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

defaults:
  - scope:
      path: "assets/images"
    values:
      image: true

disqus:
  shortname: opensfera

google_analytics: UA-110124968-1
